# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TEST_LOCATION: test_report
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile cover.out -json > report.out

    - name: Coverage Report
      run: go tool cover -html=cover.out -o coverage.html

    
    - name: Convert Report
      run: |
        go install github.com/jstemmer/go-junit-report@latest
        go generate ./...
        go-junit-report -input report.out -parser gojson -out report.xml  

    - name: Upload the coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage.html

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: report.xml
        path: report.xml
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: report.xml
        path: ${{ env.TEST_LOCATION }}
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          ${{ env.TEST_LOCATION }}/**/*.xml
