# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test > test.out

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: test_output
        path: ./test.out
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: test_output
        path: ./download
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        # token: ${{ secrets.PAT }}
        commit-message: Update test report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: example-patches
        delete-branch: true
        title: 'Update test report'
        body: |
          Update report
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          report
          automated pr
        assignees: chxx
        reviewers: chxx
        draft: false
