# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  pull_request:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: chxx-exp-4z7v1j
  BQ_DATASET_ID: test_coverage
  BQ_TABLE_ID: coverage


jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TEST_LOCATION: test_report
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test coverage
      run: |
        go test ./... -coverprofile ${{ github.workspace }}/cover.out
        go tool cover -func ${{ github.workspace }}/cover.out | grep total | awk '{print $3}'
        echo "PERCENTAGE=$(go tool cover -func ${{ github.workspace }}/cover.out | grep total | awk '{print $3}')" >> $GITHUB_OUTPUT
        '{"component":${{ github.workspace }},"coverage":$PERCENTAGE}' > bq_data.json
        cat bq_data.json
    
    - id: Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Load BigQuery data
      run: |
        bq load \
        --noreplace \
        --autodetect \
        --schema_update_option=ALLOW_FIELD_ADDITION \
        --source_format=NEWLINE_DELIMITED_JSON \
        $BQ_DATASET_ID.$BQ_TABLE_ID \
        bq_data.json
